window.BANNED_WORDS = [
  "abortion",
    "accessible",
    "accessibility",
    "activism",
    "activists",
    "advocacy",
    "advocate",
    "advocates",
    "affirmative action",
    "affirmative action programs",
    "affirming care",
    "affordable home",
    "affordable housing",
    "agricultural water",
    "agrivoltaics",
    "air pollution",
    "all-inclusive",
    "allyship",
    "alternative energy",
    "anti-racism",
    "antiracist",
    "asexual",
    "assigned at birth",
    "assigned female at birth",
    "assigned male at birth",
    "at risk",
    "autism",
    "aviation fuel",
    "barrier",
    "barriers",
    "belong",
    "bias",
    "biased",
    "biased toward",
    "biases",
    "biases toward",
    "bioenergy",
    "biofuel",
    "biogas",
    "biologically male",
    "biologically female",
    "biomethane",
    "bipoc",
    "bisexual",
    "black",
    "black and latinx",
    "breastfeeding people",
    "breastfeeding person",
    "cancer moonshot",
    "carbon emissions mitigation",
    "carbon footprint",
    "carbon markets",
    "carbon pricing",
    "carbon sequestration",
    "cec",
    "changing climate",
    "chestfeed",
    "chestfeeding people",
    "chestfeeding person",
    "clean energy",
    "clean fuel",
    "clean power",
    "clean water",
    "climate",
    "climate accountability",
    "climate crisis",
    "climate change",
    "climate consulting",
    "climate model",
    "climate models",
    "climate resilience",
    "climate risk",
    "climate science",
    "climate smart agriculture",
    "climate smart forestry",
    "climate variability",
    "climate-change",
    "climatesmart",
    "climate-smart",
    "commercial sex worker",
    "community",
    "community diversity",
    "community equity",
    "confirmation bias",
    "contaminants of environmental concern",
    "continuum",
    "covid-19",
    "critical race theory",
    "cultural competence",
    "cultural differences",
    "cultural heritage",
    "cultural relevance",
    "cultural sensitivity",
    "culturally appropriate",
    "culturally responsive",
    "definition",
    "DEI",
    "DEIA",
    "DEIAB",
    "DEIJ",
    "diesel",
    "dietary guidelines/ultraprocessed foods",
    "disabilities",
    "disability",
    "disabled",
    "disadvantaged",
    "discriminated",
    "discrimination",
    "discriminatory",
    "discussion of federal policies",
    "disparity",
    "diverse",
    "diverse backgrounds",
    "diverse communities",
    "diverse community",
    "diverse group",
    "diverse groups",
    "diversified",
    "diversify",
    "diversifying",
    "diversity",
    "diversity equity",
    "diversity and inclusion",
    "diversity in the workplace",
    "diversity, equity, and inclusion",
    "diversity/equity efforts",
    "eej",
    "ej",
    "elderly",
    "electric vehicle",
    "energy conversion",
    "enhance the diversity",
    "enhancing diversity",
    "entitlement",
    "environmental justice",
    "environmental quality",
    "equal opportunity",
    "equality",
    "equitable",
    "equitableness",
    "equity",
    "equity and inclusion",
    "ethnicity",
    "excluded",
    "exclusion",
    "expression",
    "emissions",
    "enhance the diversity",
    "enhancing diversity",
    "environmental justice",
    "equal opportunity",
    "equality",
    "equitable",
    "equitableness",
    "equity",
    "ethanol",
    "ethnicity",
    "evidence-based",
    "excluded",
    "exclusion",
    "expression",
    "female",
    "females",
    "feminism",
    "fetus",
    "field drainage",
    "fostering inclusivity",
    "fluoride",
    "fuel cell",
    "gay",
    "gbv",
    "gender",
    "gender based",
    "gender based violence",
    "gender diversity",
    "gender dysphoria",
    "gender expression",
    "gender identity",
    "gender ideology",
    "gender nonconformity",
    "gender transition",
    "gender-affirming care",
    "gendered",
    "genders",
    "geothermal",
    "ghg emission",
    "ghg modeling",
    "ghg monitoring",
    "global warming",
    "green",
    "green infrastructure",
    "greenhouse gas emission",
    "greenhouse gas emissions",
    "groundwater pollution",
    "gulf of mexico",
    "h5n1/bird flu",
    "hate",
    "hate speech",
    "health disparity",
    "health equity",
    "hispanic",
    "hispanic minority",
    "historically",
    "housing affordability",
    "housing efficiency",
    "hydrogen vehicle",
    "identity",
    "ideology",
    "immigrants",
    "implicit bias",
    "implicit biases",
    "inclusion",
    "inclusive",
    "inclusive leadership",
    "inclusiveness",
    "inclusivity",
    "increase diversity",
    "increase the diversity",
    "indigenous",
    "indigenous community",
    "indigenous community/ people",
    "inequalities",
    "inequality",
    "inequitable",
    "inequities",
    "inequity",
    "injustice",
    "institutional",
    "integration",
    "intersectional",
    "intersectionality",
    "intersex",
    "issues concerning pending litigation",
    "justice40",
    "justice40 initiative",
    "key groups",
    "key people",
    "key populations",
    "latinx",
    "lesbian",
    "lgbt",
    "lgbtq",
    "lgbtqia",
    "low-emission vehicle",
    "low-income housing",
    "male dominated",
    "marginalize",
    "marginalized",
    "marijuana",
    "measles",
    "membrane filtration",
    "men who have sex with men",
    "mental health",
    "methane emissions",
    "microplastics",
    "migrant",
    "minorities",
    "minority",
    "minority serving institution",
    "most risk",
    "msi",
    "msm",
    "multicultural",
    "mx",
    "native american",
    "nci budget",
    "net-zero",
    "nonbinary",
    "non-binary",
    "non binary",
    "noncitizen",
    "non-conforming",
    "nonpoint source pollution",
    "nuclear energy",
    "nuclear power",
    "obesity",
    "opioids",
    "oppression",
    "oppressive",
    "orientation",
    "pansexual",
    "pcb",
    "peanut allergies",
    "people of color",
    "people with a uterus",
    "people-centered care",
    "person-centered",
    "person-centered care",
    "pfas",
    "pfoa",
    "photovoltaic",
    "polarization",
    "political",
    "pollution",
    "pollution abatement",
    "pollution remediation",
    "prefabricated housing",
    "pregnant people",
    "pregnant person",
    "pregnant persons",
    "prejudice",
    "privilege",
    "privileges",
    "promote",
    "promote diversity",
    "promoting diversity",
    "pronoun",
    "pronouns",
    "prostitute",
    "pyrolysis",
    "qt",
    "queer",
    "race",
    "race and ethnicity",
    "racial",
    "racial diversity",
    "racial equity",
    "racial identity",
    "racial inequality",
    "racial justice",
    "racially",
    "racism",
    "runoff",
    "rural water",
    "safe drinking water",
    "science-based",
    "sediment remediation",
    "segregation",
    "self-assessed",
    "sense of belonging",
    "sex",
    "sexual preferences",
    "sexuality",
    "social justice",
    "social vulnerability",
    "socio cultural",
    "socio economic",
    "sociocultural",
    "socioeconomic",
    "socioeconomic status",
    "soil pollution",
    "solar energy",
    "solar power",
    "special populations",
    "status",
    "stem cell or fetal tissue research",
    "stereotype",
    "stereotypes",
    "subsidized housing",
    "sustainable construction",
    "systemic",
    "systemically",
    "they/them",
    "tile drainage",
    "topics of federal investigations",
    "topics that have received attention from congress",
    "topics that have received widespread or critical media attention",
    "trans",
    "transexual",
    "transexuals",
    "transexualism",
    "transgender",
    "transgender military personnel",
    "transgender people",
    "transitional housing",
    "trauma",
    "traumatic",
    "tribal",
    "two-spirit",
    "unconscious bias",
    "under appreciated",
    "under represented",
    "under served",
    "underappreciated",
    "underprivileged",
    "underrepresentation",
    "underrepresented",
    "underserved",
    "underrepresentation",
    "underrepresented",
    "underserved",
    "understudied",
    "undervalued",
    "vaccines",
    "victim",
    "victims",
    "vulnerable",
    "vulnerable populations",
    "water collection",
    "water conservation",
    "water distribution",
    "water efficiency",
    "water management",
    "water pollution",
    "water quality",
    "water storage",
    "water treatment",
    "white privilege",
    "wind power",
    "woman",
    "women",
    "women and underrepresented",
    "women in leadership"
];